environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "6"
    - nodejs_version: "4"

platform:
  - x86
  - x64

install:
  # Get the latest stable version of Node.js
  - ps: Install-Product node $env:nodejs_version
  - npm install

# Post-install test scripts.
test_script:
  - node --version
  - npm --version
  - npm run coverage

# Don't actually build.
build: off
